Feature: Strikethrough support. Closes #6412.
ckeditor/ckeditor5-autoformat pull request #79
Opened 2020-03-17 07:44 UTC by niegowski

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Strikethrough support. Closes #6412.

2020-03-18 16:15 UTC, Reinmar commented on docs/_snippets/features/autoformat.js
> +				'strikethrough',
I think you need to add the plugin.

2020-03-18 16:19 UTC, Reinmar commented on tests/autoformat.js
> +		it( 'should replace both "~~`" with strikethrough', () => {
```suggestion
		it( 'should replace both "~~" with strikethrough', () => {
```

2020-03-18 16:20 UTC, Reinmar requested changes
As commented.

2020-03-25 11:41 UTC, jodator approved these changes
LGTM after introduced changes.

2020-03-25 11:42 UTC, merged